# Generated by Django 2.1.4 on 2019-06-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
