# Generated by Django 2.1.4 on 2019-06-13 11:16

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bloguser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bloguser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
