# Generated by Django 2.1.4 on 2019-06-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190613_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='commentstatus',
            new_name='comment_status',
        ),
    ]
