# Generated by Django 2.1.4 on 2019-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190613_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=60),
        ),
    ]
